### ISSUE TITLE
Bilder ändern

### ISSUE THREAD

**Issue by Fluffelz** [Beuteltier/beuteltier.github.io#12]
https://www.dropbox.com/s/fjet0hf0glta6o1/Fotos.zip?dl=0

**Comment by chrisse-m** [comment]
oder doch nicht?

**Comment by chrimohr** [comment]
@Fluffelz Fotos von Piet mit weißem Hintergrund...ich mache heute mal eine Beispielseite damit wir entscheiden können ob weiß oder schwarz
