### ISSUE TITLE
seperat zu separat ändern

### ISSUE THREAD

**Issue by Fluffelz** [Beuteltier/beuteltier.github.io#15]
im über uns text @chrisse-m

**Comment by chrimohr** [comment]
@Fluffelz OK mache ich morgen habe den Computer schon aus

**Comment by Fluffelz** [comment]
Jo

Von meinem iPhone gesendet

**Comment by chrimohr** [comment]
Habs doch geändert... Geht auch online... Hättest du auch hinbekommen :D. Kann ich dir nochmal zeigen wie das geht.
