### ISSUE TITLE
Bilder mit Piet (oder Frederik)

### ISSUE THREAD

**Issue by Fluffelz** [Beuteltier/beuteltier.github.io#17]
Nach dem wir sie gemacht haben, einfügen

**Comment by chrimohr** [comment]
Habe meinen Dad gefragt...Samstag Nachmittag also so ca 15 Uhr müsste gehen

**Comment by chrimohr** [comment]
@Fluffelz sind in der Dropbox (hast ein link bekommen) bitte bearbeiten und mir schicken
