### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by chrimohr** [Beuteltier/beuteltier.github.io#3]
@Fluffelz  Icon designen und @chrisse-m einfügen

**Comment by Fluffelz** [comment]
Kann das Icon auch rund sein? .ico hab ich nicht btw.
![bildschirmfoto 2016-04-10 um 17 38 41](https://cloud.githubusercontent.com/assets/18369830/14411255/186921a6-ff43-11e5-86af-63d3ac5e353a.png)

**Comment by chrimohr** [comment]
jo rund pass muss halt transparent sein! 
man kann online zu .ico konvertieren @Fluffelz

**Comment by Fluffelz** [comment]
achso von .png oder von .ai? Transparent ist schon

**Comment by chrimohr** [comment]
@Fluffelz äää kp icon ist drin
