### ISSUE TITLE
"Über uns" box nur oben und unten

### ISSUE THREAD

**Issue by chrimohr** [Beuteltier/beuteltier.github.io#7]
@Fluffelz du musst alle Bilder transparent und alle in der gleichen Größe schicken, dann failt das auch nicht mehr->die box wird immer gleich groß

**Comment by Fluffelz** [comment]
![uberuns](https://cloud.githubusercontent.com/assets/18369830/14412299/aa473cc2-ff5f-11e5-92d7-a3a0e929ef35.png)

**Comment by Fluffelz** [comment]
Hier ist die Über uns datei
https://www.dropbox.com/s/ns5ky0m3czzbk59/%C3%9CberUns.png?dl=0

**Comment by Fluffelz** [comment]
Und hier sind alle Motive mit Kasten
https://www.dropbox.com/s/6ob93mfp9gu5hmx/Motive%20TP.zip?dl=0
